# Generated by Django 5.2.12 on 2026-03-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_update_blocked_competitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_names', models.CharField(blank=True, default='', max_length=500)),
                ('therapeutic_class', models.CharField(blank=True, default='', max_length=200)),
                ('indications', models.TextField(blank=True, default='')),
                ('dosage', models.TextField(blank=True, default='')),
                ('contraindications', models.TextField(blank=True, default='')),
                ('interactions', models.TextField(blank=True, default='')),
                ('adverse_effects', models.TextField(blank=True, default='')),
                ('mechanism', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drugs',
                'indexes': [models.Index(fields=['generic_name'], name='drugs_generic_b58053_idx')],
            },
        ),
    ]
