# Generated by Django 5.2.12 on 2026-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_add_drug_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
