# Generated by Django 5.2.12 on 2026-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_add_timeout_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workflows.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workflows.user')),
            ],
            options={
                'db_table': 'feedbacks',
                'indexes': [models.Index(fields=['user'], name='feedbacks_user_id_25d2e0_idx'), models.Index(fields=['-created_at'], name='feedbacks_created_d13da7_idx'), models.Index(fields=['rating'], name='feedbacks_rating_109b6e_idx')],
            },
        ),
    ]
