# Generated by Django 5.2.12 on 2026-03-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_add_feedback_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('tokens_input', models.IntegerField()),
                ('tokens_output', models.IntegerField()),
                ('tokens_cache_write', models.IntegerField(default=0)),
                ('tokens_cache_read', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_logs', to='workflows.user')),
            ],
            options={
                'db_table': 'cost_logs',
                'indexes': [models.Index(fields=['user'], name='cost_logs_user_id_f77880_idx'), models.Index(fields=['-created_at'], name='cost_logs_created_78a6bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('latency_ms', models.IntegerField(null=True)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='workflows.user')),
            ],
            options={
                'db_table': 'tool_executions',
                'indexes': [models.Index(fields=['tool_name'], name='tool_execut_tool_na_653899_idx'), models.Index(fields=['-created_at'], name='tool_execut_created_7af9ed_idx')],
            },
        ),
    ]
