# Generated by Django 5.2.12 on 2026-03-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_add_costlog_toolexecution'),
        ('workflows', '0011_add_feedback_configs'),
    ]

    operations = [
    ]
