# Generated by Django 5.2.12 on 2026-03-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_seed_initial_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confighistory',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
