# Generated by Django 5.2.12 on 2026-03-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0017_config_history_old_value_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("node", models.CharField(max_length=100)),
                ("error_type", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                ("trace_id", models.CharField(blank=True, default="", max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to="workflows.user",
                    ),
                ),
            ],
            options={
                "db_table": "error_logs",
                "indexes": [
                    models.Index(fields=["node"], name="error_logs_node_745db2_idx"),
                    models.Index(fields=["-created_at"], name="error_logs_created_e08e60_idx"),
                ],
            },
        ),
    ]
